name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if (Test-Path -Path "dev-requirements.txt") { pip install -r dev-requirements.txt }
    - name: Run linters and type checks
      run: |
        # run ruff and mypy if available
        python -c "import subprocess,sys
import shutil
has_ruff=shutil.which('ruff')
has_mypy=shutil.which('mypy')
print('ruff:',has_ruff,'mypy:',has_mypy)
sys.exit(0)"
    - name: Run tests
      run: |
        python -m pytest -q
